image: Visual Studio 2013

platform: x64

install:
  - set QTDIR=C:\Qt\5.6\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin;
  
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=debug -DBUILD_SHARED_LIBS=OFF ..
  
build_script:
  - make
  - make test
