image: Visual Studio 2013

platform: 
  - x64
  - x86

configuration: Debug
  
before_build:
  - set VS_VERSION=Visual Studio 12 2013
  - if "%platform%" == "x64" set VS_FULL=%VS_VERSION% Win64
  - if "%platform%" == "x64" set QTDIR=C:\Qt\5.6\msvc2013_64
  - if "%platform%" == "x86" set VS_FULL=%VS_VERSION%
  - if "%platform%" == "x86" set QTDIR=C:\Qt\5.6\msvc2013
  - set PATH=%PATH%;%QTDIR%\bin;
  - mkdir build
  - cd build
  - cmake -G "%VS_FULL%" -DCMAKE_BUILD_TYPE=debug -DBUILD_SHARED_LIBS=OFF ..
#  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
#  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - dir
  
build_script:
  - cmake --build . --target install
  - dir
  
test_script:
  - ctest -C Debug

